name: Push Docker Image to AWS ECR

on:
  push:
    branches:
      - "main"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Cache Next.js build cache
        id: cache-nextjs
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-cache-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create .env file
        run: |
          set -e
          echo "${{ secrets.ENV_PROD }}" > .env
          cat .env

      - name: Build Frontend Docker image
        run: |
          docker build --no-cache \
            --build-arg ENV_FILE=.env \
            -f Dockerfile.prod \
            -t 211125602993.dkr.ecr.ap-northeast-2.amazonaws.com/mileque/front:latest .

      - name: Build Frontend Nginx Docker image
        run: |
          docker build -t 211125602993.dkr.ecr.ap-northeast-2.amazonaws.com/mileque/front-nginx:latest ./nginx

      - name: Push Frontend Docker images to ECR
        run: |
          docker push 211125602993.dkr.ecr.ap-northeast-2.amazonaws.com/mileque/front:latest
          docker push 211125602993.dkr.ecr.ap-northeast-2.amazonaws.com/mileque/front-nginx:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster mileque-cluster --service mileque-front-service --force-new-deployment

      - name: Slack Notification on Success
        if: success()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "blocks": [
                { "type": "divider" },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: *Pushed image to AWS ECR for Deployment!*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*\n${{ github.ref }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*\n${{ github.sha }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name*\n${{ github.event_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow*\n${{ github.workflow }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job ID*\n${{ github.run_id }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Duration*\n${{ github.run_duration_ms }} ms"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Action"
                      },
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEVOPS_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "blocks": [
                { "type": "divider" },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":x: *Failed to Push image to AWS ECR for Deployment* :x:"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*\n${{ github.ref }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*\n${{ github.sha }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name*\n${{ github.event_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow*\n${{ github.workflow }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job ID*\n${{ github.run_id }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Duration*\n${{ github.run_duration_ms }} ms"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Action"
                      },
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEVOPS_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
